### ISSUE TITLE
error message: not valid/supported format

### ISSUE THREAD

**Issue by og900aero** [AnirudhG07/archivemount.yazi#2] opened 2024-08-14 08:50 UTC
I use yazi 0.3.0 from git, and installed archivemount.yazi with ya pack -a AnirudhG07/archivemount command.
When I use mount function on .tar.gz or .zip files, I get error message: "Selected file is not a valid/supported archive"

yazi -V
Yazi 0.3.0 (c75960e 2024-08-14)

**Comment by AnirudhG07** [comment] 2024-08-14 11:40
Yes, some formats are not supported by archivemount command itself.
For example .zip, you maybe able to mount it, but when you are unmounting, it converts it to tar, instead of zip, which creates an issue.

However .tar.gz one should work. Its a bug in the code, ill fix that asap.

**Comment by og900aero** [comment] 2024-08-14 11:55
> Yes, some formats are not supported by archivemount command itself. For example .zip, you maybe able to mount it, but when you are unmounting, it converts it to tar, instead of zip, which creates an issue.
> 
> However .tar.gz one should work. Its a bug in the code, ill fix that asap.

I try with example.tar.gz, but I get error message too.

**Comment by AnirudhG07** [comment] 2024-08-14 11:56
But one thing i can do is to make the rename the unmounted zip final file to tar, so that things become comfortable.

**Comment by AnirudhG07** [comment] 2024-08-14 11:58
Yes, i ll get everything fixed by tonight. Ill make sure that zips and tar,gz also work.

**Comment by og900aero** [comment] 2024-08-14 12:30
> Yes, i ll get everything fixed by tonight. Ill make sure that zips and tar,gz also work.

Okay, thank u so much.
However I try archivemount in terminal, but works fine with zip.
1. I mounted zip file with archivemount example.zip /home/Data/tmp
2. Then I delete file from mounted directory, and modified one txt file.
3. unmount mounted zip file with: fusermount -u /home/Data/tmp/example.zip-archivemount
4. The original zip file renamed example.zip.orig
5. The modified zip file name is example.zip

So nothing tar appear to me in original archivemount (Debian 12).

**Comment by AnirudhG07** [comment] 2024-08-14 16:59
I am unable to reproduce your steps
1) I made a zip file
2) archivemount example.zip mountpoint (mountpoint is an empty directory i made)
3) modifications to mountpoint like deleting and editing
4) fusermount -u mountpoint
Then i got 2 files, example.zip.orig and example.zip
5) `file example.zip.orig` shows ZIP archive while `file example.zip` shows TAR archive

**Comment by AnirudhG07** [comment] 2024-08-14 18:03
I have fixed .tar.gz and allowed .zip usages, although .zip is still not very clean, since .tar file should be made, instead, .zip is made, this your yazi previewer may give you warnings.
Also if you rename example.zip.prig to example.zip, that also will throw warnings. Ill try to see to it that tomorrow.

**Comment by og900aero** [comment] 2024-08-15 05:05
> I have fixed .tar.gz and allowed .zip usages, although .zip is still not very clean, since .tar file should be made, instead, .zip is made, this your yazi previewer may give you warnings. Also if you rename example.zip.prig to example.zip, that also will throw warnings. Ill try to see to it that tomorrow.

Ooo. The mime-type changed. I see now. I try the new version, moment.

**Comment by og900aero** [comment] 2024-08-15 05:20
> I have fixed .tar.gz and allowed .zip usages, although .zip is still not very clean, since .tar file should be made, instead, .zip is made, this your yazi previewer may give you warnings. Also if you rename example.zip.prig to example.zip, that also will throw warnings. Ill try to see to it that tomorrow.

Thx, working fine now! I write ticket to archivemount. Maybe repair this problem, because I often use tar.zst format too, because speed and compress.

**Comment by AnirudhG07** [comment] 2024-08-15 05:24
I will try to automatically get the zip files to be made into tar files, by auto renaming them.

I will close this issue for now. Thanks for pointing out the BUG!

**Comment by og900aero** [comment] 2024-08-21 08:01
I get response from archivemount's developer from the bug (rename to TAR):

[https://github.com/cybernoid/archivemount/issues/30#issuecomment-2298965227](https://github.com/cybernoid/archivemount/issues/30#issuecomment-2298965227)

**Comment by AnirudhG07** [comment] 2024-08-21 11:25
I see, I have to think about to switch to the mentioned new archivemount or not. I mean, i only have to change the command arguments at max.
Have you used it? What are your thoughts? Is it easier to use than archivemount?

**Comment by og900aero** [comment] 2024-08-21 11:46
> I see, I have to think about to switch to the mentioned new archivemount or not. I mean, i only have to change the command arguments at max. Have you used it? What are your thoughts? Is it easier to use than archivemount?

I honestly don't know how to put this right now. Is it a separate package at all, or does the already existing archivemount have to be patched somehow?

**Comment by AnirudhG07** [comment] 2024-08-23 06:17
Ill get back to it later on, if required to change. It is not very straightforward and needs a bit of digging into. Thanks for the info though!

**Closed as completed by AnirudhG07** 2024-08-23 06:17 UTC
